services:
  - type: web
    name: neuro-candombe-api
    env: python
    plan: starter
    buildCommand: pip install -r requirements-api.txt
    startCommand: uvicorn src.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
      - key: MODEL_PATH
        value: models/candombe_epoch5.pt
